# COURSE: A deep understanding of deep learning
## SECTION: Math prerequisites
### LECTURE: Matrix multiplication
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202305

In [1]:
# import libraries
import numpy as np
import torch

# Using numpy

In [4]:
# create some random matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# try some multiplications...
print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@C   ,2)), print(' ')
# print(np.round( B@C   ,2)), print(' ')
print(np.round( C.T@A ,2))

[[ 0.75 -0.95 -3.84  2.01  2.25]
 [-3.04 -3.41 -6.94  4.83 -3.53]
 [ 0.45 -0.2   1.17  1.81 -2.64]]
 
[[-0.32 -0.91 -1.01  1.03]
 [ 2.7  -2.52  1.51 -3.13]
 [ 3.97 -6.21  2.37 -4.2 ]
 [-0.17  0.2   0.05  0.11]
 [-0.17  1.63 -0.33  0.03]
 [ 1.54 -2.66  2.25 -2.27]
 [ 1.21 -0.63  0.7  -1.52]]


# Using pytorch

In [8]:
# create some random matrices
A  = torch.randn(3,4)
B  = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor( C1,dtype=torch.float )

# try some multiplications...
print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@B.T ,2)), print(' ')
print(np.round( A@C1  ,2)), print(' ')
print(np.round( A@C2  ,2))

tensor([[ 0.7500,  2.0100, -1.7600,  2.8200,  1.0600],
        [ 1.5000, -2.3500,  2.4500, -2.1700, -4.1600],
        [ 1.0600, -1.0900,  3.1200, -5.9100, -2.3500]])
 
tensor([[-0.7000,  0.1200, -1.0000,  3.4300,  0.6600,  0.7700,  2.4000],
        [-0.9400, -2.7700,  0.8200,  0.2300, -0.9600, -2.1700,  0.4600],
        [-2.5500, -2.1400,  1.4000,  3.0600, -1.4200, -4.5700, -0.8000]],
       dtype=torch.float64)
 
tensor([[-0.7000,  0.1200, -1.0000,  3.4300,  0.6600,  0.7700,  2.4000],
        [-0.9400, -2.7700,  0.8200,  0.2300, -0.9600, -2.1700,  0.4600],
        [-2.5500, -2.1400,  1.4000,  3.0600, -1.4200, -4.5700, -0.8000]])
